title: Brian Osgood
description: Brian Osgood Website # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https//:osgoodb.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Brian Osgood
tagline: Budding Data Scientist
about-description: A student at General Assembly Seattle. I am taking their Data Science Immersive Course
pic:   # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: osgoodbl@gmail.com # Add your Email address
phone: (253) 548-5243 # Add your Phone number
website: ' '  # Add your website, do not add http://
linkedin: brianosgood # Add your Linkedin handle
github: osgoodbl # Add your Github handle
twitter: ' ' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
